### ISSUE TITLE
Fixes for Build on Mac

### ISSUE THREAD

**Issue by JohnSchwitz** [vpavkin/i-have-money#1]
Wonderful Job.  

I believe the vm within a vm causes issues on the **build on a mac**.  On sbt writeBackend/run  and sbt readBackend/run 
Failed to bind to: /127.0.0.1:9101.  
On sbt writeFrontend/run and sbt readFrontend/run 
listening on addresses [akka.tcp://IHaveMoneyWriteFront@127.0.0.1:10101]. 
My docker machine ip is 192.168.99.100.  Could 9101 and 10101 be mapped to different addresses also?  I do not know how to discover these.

I have a pre 2010 mac so I use Docker Toolbox.  This is not the quality of your distribution, it is the mac vm with a vm problem.  

Do you have suggestions for changing the build file?

**Comment by vpavkin** [comment]
Hey! Thanks for kind words!:)
For launching with docker there is sbt-docker build and some bash scripts. 
So if you wish to use docker, this is what you have to do:

``` bash
sbt iHaveMoney/docker # this will build docker images for all 4 apps
./docker-all-vm.sh # this is a helper script that launches all 4 apps with different ports.
```

All configuration is overridable via env variables, so check these sh scripts to see how you can supply different ports if you need :)

**Comment by JohnSchwitz** [comment]
Vladimir,

Your project is truly a gem.  Your instructions were excellent on your github site.  

I continually have problems with the Mac environment on docker and db's.  Therefore; I am setting up a dev environment with a VM on the mac or on Google.  I will report back success.

John

**Comment by JohnSchwitz** [comment]
I cannot build sbt readBackend/run.  I get 

| => sbt readBackend/run
[info] Loading global plugins from /Users/johnschwitz/.sbt/0.13/plugins
[info] Loading project definition from /Users/johnschwitz/i-have-money/project
[info] Set current project to iHaveMoney (in build file:/Users/johnschwitz/i-have-money/)
[info] Running ru.pavkin.ihavemoney.readback.ReadBackend 
Starting IHaveMoney read backend...
[INFO] [10/16/2016 19:45:52.652] [run-main-0] [akka.remote.Remoting] Starting remoting
[INFO] [10/16/2016 19:45:52.845] [run-main-0] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://iHaveMoneyReadBackend@127.0.0.1:9201]
[INFO] [10/16/2016 19:45:52.848] [run-main-0] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://iHaveMoneyReadBackend@127.0.0.1:9201]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] [10/16/2016 19:45:58.190] [iHaveMoneyReadBackend-akka.actor.default-dispatcher-4] [akka.tcp://iHaveMoneyReadBackend@127.0.0.1:9201/user/projectionMonitor/MoneyViewProjection/MoneyViewProjection-supervised] Persistence failure when replaying events for persistenceId [MoneyViewProjection]. Last known sequence number [0]
java.sql.SQLTimeoutException: Timeout after 1004ms of waiting for a connection.
    at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227)
    at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182)
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93)
    at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:12)
    at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415)
    at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414)
    at slick.jdbc.JdbcBackend$BaseSession.startInTransaction(JdbcBackend.scala:437)
    at slick.driver.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:41)
    at slick.driver.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:38)
    at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
    at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: JDBC4 Connection.isValid() method not supported, connection test query must be configured
    at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:441)
    at com.zaxxer.hikari.pool.BaseHikariPool$1.run(BaseHikariPool.java:413)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

I have a docker postgresql on 192.168.99.100:5432.  The other three modules build!  Is there a problem with leaving a setting at 127.0.0.1 or with port 9201?  I changed configuration from 127.0.0.1 to 192.168.99.100 for anything with port 5432.
